### ISSUE TITLE
guacd not installed by default

### ISSUE THREAD

**Issue by cosmicvibes** [mrlesmithjr/ansible-guacamole#58]
I've just run fresh install with all the default settings, and it appears that guacd is no longer installed by default.

I think this happened here: https://github.com/mrlesmithjr/ansible-guacamole/commit/6a5588c9d1706632e23397139503ce19da121a35

...and is because no default "guacd_config" option is defined in "defaults/main.yml".

Is this intentional? I worked around it by defining a "guacd_config" option in my playbook, but to me it seems odd that this is not the default. Or at least maybe it should be mentioned on the documentation?

I am happy to raise a pull request either way, but would first like to see what the intended behaviour here is.

Thanks kindly for your work on this.

**Comment by mrlesmithjr** [comment]
@roumano - Do you have any thoughts on this?

**Comment by roumano** [comment]
Hi, yes sorry it's my fault : 
i confirm `guacd_config` should be enable by default (so need it on `defaults/main.yml`) (and in the doc too)
if you are comfortable, yes, please do a pull request it's a simple change. Otherwise i can repair my fault if you prefer.

Regards

**Comment by cosmicvibes** [comment]
Pull request submitted: https://github.com/mrlesmithjr/ansible-guacamole/pull/60 many thanks!

**Comment by roumano** [comment]
Issue fixed with https://github.com/mrlesmithjr/ansible-guacamole/pull/60

Thank you @cosmicvibes
