### ISSUE TITLE
Create users also for databases

### ISSUE THREAD

**Issue by stdevel** [mrlesmithjr/ansible-guacamole#9]
First of all - thanks a lot for your role - it's has been really useful for me. 👍🏻 

I saw that there is the variable `guacamole_users` - it creates users and also connections - but only for the integrated user management. I think it would also be useful to have this for installations using MySQL/MariaDB or PostgreSQL - what do you think?

Best wishes,
Christian.

**Comment by mrlesmithjr** [comment]
@stdevel Glad you've had some good use of this role. I do agree that adding DB functionality would be useful. I think at one point I started to go this route but never finished or started ;)
